# Generated by Django 4.2.5 on 2023-09-21 08:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userauth", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="appuser",
            managers=[],
        ),
    ]
