# Generated by Django 4.2.5 on 2023-09-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauth", "0002_alter_appuser_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appuser",
            name="username",
        ),
        migrations.AlterField(
            model_name="appuser",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
